name: Create release upon tag creation
 
# Version tags intended for release should be in the SemVer format of vX.Y.Z or vX.Y.Z-A.B, 
# where X represents the major number, Y represents the minor number, Z represents the
# patch number, A represents the pre-release type (e.g. beta or rc), and B represents the
# number for that pre-release type.

# Examples: 'v1.0.0', 'v1.0.0-rc.1'

on: # Only run on new version tag push
  push:
    tags: 
      - "v*.*.*"
      - "v*.*.*-*"

permissions:
  contents: write
  
jobs:
  check-tag:
    name: Check version tag syntax before continuing
    outputs:
      valid: ${{ steps.check.outputs.valid }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate version name
        id: check
        env:
          TAG_STRING: "${{ github.ref_name }}"
        run: |
          REGEX='^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z-]+\.[0-9]+)?$'

          if [[ "$TAG_STRING" =~ $REGEX ]]; then
            printf "Tag \"%s\" is a valid version tag!\n" "$TAG_STRING"
            printf "valid=%s\n" "true" >> $GITHUB_OUTPUT
          else
            printf "Tag \"%s\" is NOT a valid version tag!\n" "$TAG_STRING"
            printf "valid=%s\n" "false" >> $GITHUB_OUTPUT
          fi
  release:
    name: Publish release
    needs: check-tag
    if: needs.check-tag.outputs.valid == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Determine whether version tag is prerelease
        env:
          TAG_STRING: "${{ github.ref_name }}"
        run: |
          REGEX='-[a-zA-Z0-9.-]+$'

          if [[ "$TAG_STRING" =~ $REGEX ]]; then
            printf 'Tag \"%s\" is a prerelease tag!\n' "$TAG_STRING"
            printf "TAG_IS_PRERELEASE=%s\n" "true" >> $GITHUB_ENV
          else
            printf 'Tag \"%s\" is NOT a prerelease tag!\n' "$TAG_STRING"
            printf "TAG_IS_PRERELEASE=%s\n" "false" >> $GITHUB_ENV
          fi
      - name: Create GitHub Release
        id: create-release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3
        with:
          draft: true
          prerelease: ${{ env.TAG_IS_PRERELEASE == 'true' }}
          generate_release_notes: true
      - name: Create GitHub Release notification summary
        run: |
          printf "# 🎉 Release ready!\n\n" >> $GITHUB_STEP_SUMMARY
          printf "The link to the release (tag **%s**, ID **%s**) is: %s\n\n" \
            "${{ github.ref_name }}" \
            "${{ steps.create-release.outputs.id }}" \
            "${{ steps.create-release.outputs.url }}" \
            >> $GITHUB_STEP_SUMMARY
          printf "Note that the release is still yet unpublished, \
          so you will need to manually publish it.\n\n" \
            >> $GITHUB_STEP_SUMMARY
          printf "Generated at: %s\n" \
            "$(date -u +"%Y-%m-%d %H:%M:%S UTC")" \
            >> $GITHUB_STEP_SUMMARY
