name: Validate Renovate config files

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths-ignore:
      - ".github/**" # Avoid issues with .github files
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  validate-config:
    name: Validate config
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Create list of files to validate
        id: files
        run: |
          set -euo pipefail
          
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          # We want to only do files that will be used by other repositories
          files=$(git ls-files -- '*.json*' ':!:.github')
          
          {
            echo "files<<$EOF"
            echo "$files"
            echo "$EOF"
          } >> "$GITHUB_OUTPUT"
      - name: Validate Renovate config files
        uses: suzuki-shunsuke/github-action-renovate-config-validator@ee9f69e1f683ed0d08225086482b34fc9abe9300 # v2.1.0
        with:
          config_file_path: ${{ steps.files.outputs.files }}
