name: Validate Renovate config files

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths-ignore:
      - ".github/**" # Avoid issues with .github files
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  flake-check:
    name: Check flake
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Create list of files to validate
        id: files
        run: |
          set -euo pipefail
          
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          # We want to only do files that will be used by other repositories
          files=$(git ls-files -- '*.json*' ':!:.github')
          
          {
            echo "files<<$EOF"
            echo "$files"
            echo "$EOF"
          } >> "$GITHUB_OUTPUT"
      - name: Validate Renovate config files
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v2
        with:
          config_file_path: ${{ steps.files.outputs.files }}
